shopping/forms.py
# Authored by: Yat Nam, Jacob, Keirav
# forms for entering shopping list
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField
from wtforms.validators import DataRequired

class CreateListForm(FlaskForm):
    listName = StringField(validators=[DataRequired()], render_kw={"placeholder": "Shopping List Name"})
    submit = SubmitField("Next")

class AddItemForm(FlaskForm):
    newItem = StringField(validators=[DataRequired()], render_kw={"placeholder": "Food Item"})
    itemQuantity = IntegerField(validators=[DataRequired()], render_kw={"placeholder": "Quantity"})
    itemUnits = StringField(validators=[DataRequired()], render_kw={"placeholder": "Units (e.g., g, ml)"})
    submit = SubmitField("Add Item")





class NewListForm(FlaskForm):
    listName = StringField(validators=[DataRequired()])
    submit = SubmitField()

shopping/views.py
# View functions for the shopping HTML template
# Authored by Jacob Norman and Yat Nam Chan

from flask import render_template, flash, redirect, url_for, Blueprint, request
from flask_login import current_user, login_required

from models import ShoppingList, ShoppingItem
from shopping.forms import AddItemForm, CreateListForm
from shopping.shopping_util import create_shopping_list_util, create_shopping_item, \
    delete_shopping_item, delete_shopping_list, mark_shopping_list_as_complete

shopping_blueprint = Blueprint('shopping', __name__, template_folder='templates')


# Base view function that initially renders shopping list page
@shopping_blueprint.route('/shopping_list', methods=['GET'])
@login_required
def shopping_list():
    user_shopping_lists = ShoppingList.query.filter_by(user_id=current_user.id).all()
    return render_template('shopping/shopping_list.html', shopping_lists=user_shopping_lists)


# takes user input of a new list name, creates that list then redirects user to a page to add first items to the list
@shopping_blueprint.route('/create_shopping_list', methods=['GET', 'POST'])
@login_required
def create_shopping_list():
    form = CreateListForm()
    if request.method == 'POST' and form.validate_on_submit():
        list_name = form.listName.data
        s_list = create_shopping_list_util(current_user.id, list_name)
        flash("Shopping list created", "success")
        return redirect(url_for('shopping.shopping_list_detail', list_id=s_list.id))
    return render_template('shopping/create_shopping_list.html', form=form)


# View function that renders an already existing shopping lists they have and allows user to modify them
@shopping_blueprint.route('/shopping_list_detail/<int:list_id>', methods=['GET', 'POST'])
@login_required
def shopping_list_detail(list_id):
    s_list = ShoppingList.query.get_or_404(list_id)
    form = AddItemForm()
    if request.method == 'POST' and form.validate_on_submit():
        food_item_name = form.newItem.data
        quantity = form.itemQuantity.data
        units = form.itemUnits.data

        create_shopping_item(list_id, food_item_name, quantity, units)

        flash("Item added to shopping list", "success")
        return redirect(url_for('shopping.shopping_list_detail', list_id=list_id))

    return render_template('shopping/shopping_list_detail.html', form=form, shopping_list=s_list)


# View function to delete a shopping list in its entirety
@shopping_blueprint.route('/delete_list/<int:list_id>', methods=['POST'])
@login_required
def delete_list(list_id):
    s_list = ShoppingList.query.get_or_404(list_id)
    if s_list.user_id != current_user.id:
        flash('Unauthorized', 'error')
        return redirect(url_for('shopping.shopping_list'))

    delete_shopping_list(s_list)
    flash('Shopping list deleted', 'success')
    return redirect(url_for('shopping.shopping_list'))


# View function for deleting a food item from a shopping list
@shopping_blueprint.route('/delete_item/<int:item_id>', methods=['POST'])
@login_required
def delete_item(item_id):
    shopping_item = ShoppingItem.query.get_or_404(item_id)
    s_list = shopping_item.get_slist()
    if s_list.user_id != current_user.id:
        flash('Unauthorized', 'error')
        return redirect(url_for('shopping.shopping_list_detail', list_id=shopping_item.list_id))

    delete_shopping_item(item_id)
    flash('Item deleted from shopping list', 'success')
    return redirect(url_for('shopping.shopping_list_detail', list_id=shopping_item.list_id))


# View function to move a single item from shopping list to pantry
@shopping_blueprint.route('/list_to_pantry/<int:item_id>', methods=['POST'])
@login_required
def list_to_pantry(item_id):
    shopping_item = ShoppingItem.query.get_or_404(item_id)
    return redirect((url_for('shopping.shopping_list_detail', list_id=shopping_item.list_id)))

# Example usage in the route
@shopping_blueprint.route('/complete_list/<int:list_id>', methods=['POST'])
@login_required
def complete_list(list_id):
    shopping_list = ShoppingList.query.get_or_404(list_id)
    if shopping_list.user_id != current_user.id:
        flash('Unauthorized', 'error')
        return redirect(url_for('shopping.shopping_list'))

    mark_shopping_list_as_complete(shopping_list)

    flash('Shopping list completed and items moved to pantry', 'success')
    return redirect(url_for('shopping.shopping_list'))



templates/shopping/add_items_to_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Items to Shopping List</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Roboto', sans-serif;
            background: #f7f7f7;
            margin: 0;
            padding: 20px;
        }
        header {
            background-color: #f6f6f6;
            padding: 10px;
            text-align: center;
            margin-bottom: 20px;
            position: relative;
        }
        button {
            background: #0056b3;
            border: none;
            color: white;
            padding: 10px 20px;
            border-radius: 4px;
            cursor: pointer;
            margin: 0 10px;
        }
        button:hover {
            background: #004494;
        }
        .container {
            padding: 20px;
            background: white;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
            border-radius: 8px;
            margin-top: 40px;
        }
        .shopping-item {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px;
            margin-bottom: 10px;
            border-bottom: 1px solid #ccc;
        }
        .delete-button {
            background-color: #f44336;
            color: white;
            border: none;
            border-radius: 4px;
            padding: 5px 10px;
            cursor: pointer;
        }
        .delete-button:hover {
            background-color: #d32f2f;
        }
        .field {
            margin-bottom: 20px;
        }
        .field .control {
            margin-bottom: 10px;
        }
    </style>
</head>
<body>
    <header>
        <button onclick="location.href='{{ url_for('shopping.shopping_list') }}'" style="position: absolute; left: 20px;">Back to Shopping Lists</button>
    </header>
    <div class="container">
        <h1>Add Items to Shopping List: {{ list_name }}</h1>
        {% if form %}
        <form method="POST" action="{{ url_for('shopping.add_items_to_list', list_id=list_id) }}">
            {{ form.hidden_tag() }}
            <div class="field">
                <div class="control">
                    {{ form.newItem(class="input", placeholder="Add new item") }}
                </div>
            </div>
            <div class="field">
                <div class="control">
                    {{ form.itemQuantity(class="input", placeholder="Enter quantity") }}
                </div>
            </div>
            <div class="field">
                <div class="control">
                    {{ form.itemUnits(class="input", placeholder="Enter units (g or ml)") }}
                </div>
            </div>
            <div>
                {{ form.submit(class="button is-info is-centered") }}
            </div>
        </form>
        {% endif %}
        <h2>List of Items</h2>
        {% for item in items %}
            <div class="shopping-item">
                <span>{{ item.qfooditem.fooditem.name }} (Quantity: {{ item.qfooditem.quantity }} {{ item.qfooditem.units }})</span>
                <form action="{{ url_for('shopping.delete_item', item_id=item.id) }}" method="POST">
                    <button class="delete-button" type="submit">X</button>
                </form>
            </div>
        {% endfor %}
    </div>
</body>
</html>

templates/shopping/create_shopping_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Shopping List</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Roboto', sans-serif;
            background: #f7f7f7;
            margin: 0;
            padding: 20px;
        }
        header {
            background-color: #f6f6f6;
            padding: 10px;
            text-align: center;
            margin-bottom: 20px;
            position: relative;
        }
        button {
            background: #0056b3;
            border: none;
            color: white;
            padding: 10px 20px;
            border-radius: 4px;
            cursor: pointer;
            margin: 0 10px;
        }
        button:hover {
            background: #004494;
        }
        .back-button {
            position: absolute;
            left: 20px;
            top: 50%;
            transform: translateY(-50%);
        }
        .container {
            padding: 20px;
            background: white;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
            border-radius: 8px;
            margin-top: 20px; /* Add spacing between button and container */
        }
        .field {
            margin-bottom: 20px;
        }
        .field .control {
            margin-bottom: 10px;
        }
    </style>
</head>
<body>
    <header>
        <button onclick="location.href='/shopping/shopping_list'" class="back-button">Back to Shopping Lists</button>
    </header>
    <div class="container">
        <h1>Create New Shopping List</h1>
        {% if form %}
        <form method="POST" action="{{ url_for('shopping.create_shopping_list') }}">
            {{ form.hidden_tag() }}
            <div class="field">
                <div class="control">
                    {{ form.listName(class="input", placeholder="New shopping list name") }}
                </div>
            </div>
            <div>
                {{ form.submit(class="button is-info is-centered") }}
            </div>
        </form>
        {% endif %}
    </div>
</body>
</html>

templates/shopping/shopping_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shopping List</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet">
    <style>

        body {
            font-family: 'Roboto', sans-serif;
            background: #f7f7f7;
            margin: 0;
            padding: 20px;
        }
        header {
            background-color: #f6f6f6;
            padding: 10px;
            text-align: center;
            margin-bottom: 20px;
            position: relative;
        }
        header button {
            background: #0056b3;
            border: none;
            color: white;
            padding: 10px 20px;
            margin: 0 10px;
            border-radius: 4px;
            cursor: pointer;
        }
        header button:hover {
            background: #004494;
        }
        .container {
            padding: 20px;
            background: white;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
            border-radius: 8px;
            margin-bottom: 20px;
        }
        .shopping-list {
            margin-bottom: 20px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        .shopping-list h2 {
            display: inline;
            cursor: pointer;
        }
        .shopping-list form {
            display: inline;
        }
        .delete-button, .complete-button {
            background-color: #f44336;
            color: white;
            border: none;
            border-radius: 4px;
            padding: 5px 10px;
            cursor: pointer;
        }
        .delete-button:hover, .complete-button:hover {
            background-color: #d32f2f;
        }
        .complete-button {
            background-color: #4caf50;
            margin-left: 10px;
        }
        .complete-button:hover {
            background-color: #45a049;
        }
        .sidebar {
            height: 100%;
            width: 0;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color: #111;
            overflow-x: hidden;
            transition: width 0.3s;
            padding-top: 60px;
        }
        .sidebar a {
            padding: 10px 0px;
            text-decoration: none;
            font-size: 25px;
            color: #818181;
            display: block;
            text-align: center;
            transition: 0.3s;
        }
        .sidebar a:hover {
            color: #f1f1f1;
        }
        .sidebar .closebtn {
            position: absolute;
            top: 0;
            right: 25px;
            font-size: 36px;
        }
        .navbar {
            position: sticky;
            top: 0;
            width: 100%;
            background: #f6f6f6;
            z-index: 1;
            padding: 10px 0;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
        }
        .navbar .openbtn {
            font-size: 20px;
            cursor: pointer;
            color: white;
            border: none;
            border-radius: 4px;
            background-color: #111;
            padding: 10px;
            margin-left: 20px;
        }
        .your-button {
            width: 200px;
            text-align: center;
            padding: 10px 20px;
            background-color: #3498db;
            color: white;
            font-size: 20px;
            border-radius: 4px;
            text-decoration: none;
            transition: background-color 0.3s ease-in-out;
        }
        .your-button:hover {
            background-color: #2980b9;
        }
    </style>
</head>
<body>
<div class="navbar">
    <button class="openbtn" onclick="toggleNav()">☰ Menu</button>
    <div id="mySidebar" class="sidebar">
        <a href="javascript:void(0)" class="closebtn" onclick="toggleNav()">×</a>
        <a href="/main-menu">Main</a>
        <a href="/pantry/items">My Pantry</a>
        <a href="/pantry/search">Food Browser</a>
        <a href="/shopping/shopping_list">Shopping List</a>
        <a href="/recipes/recipes">Recipes</a>
        <a href="/barcodes/add_barcode">Save a Barcode</a>
    </div>
</div>

<div class="container">
    <h1>Shopping Lists</h1>
    {% for shopping_list in shopping_lists %}
        <div class="shopping-list" id="shopping-list-{{ shopping_list.id }}">
            <h2 onclick="location.href='{{ url_for('shopping.shopping_list_detail', list_id=shopping_list.id) }}'">{{ shopping_list.list_name }}</h2>
            <div>
                <form action="{{ url_for('shopping.complete_list', list_id=shopping_list.id) }}" method="POST" style="display:inline;">
                    <button class="complete-button" type="submit">Complete</button>
                </form>
                <form action="{{ url_for('shopping.delete_list', list_id=shopping_list.id) }}" method="POST" style="display:inline;">
                    <button class="delete-button" type="submit">X</button>
                </form>
            </div>
        </div>
    {% endfor %}
    <button class="your-button" onclick="location.href='{{ url_for('shopping.create_shopping_list') }}'">Create New Shopping List</button>
</div>

<script>
    function toggleNav() {
        var sidebar = document.getElementById("mySidebar");
        sidebar.style.width = sidebar.style.width === "250px" ? "0" : "250px";
    }
</script>
</body>
</html>

templates/shopping/shopping_list_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shopping List Details</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Roboto', sans-serif;
            background: #f7f7f7;
            margin: 0;
            padding: 20px;
        }
        header {
            background-color: #f6f6f6;
            padding: 10px;
            text-align: center;
            margin-bottom: 20px;
            position: relative;
        }
        button {
            background: #0056b3;
            border: none;
            color: white;
            padding: 10px 20px;
            border-radius: 4px;
            cursor: pointer;
            margin: 0 10px;
        }
        button:hover {
            background: #004494;
        }
        .back-button {
            position: absolute;
            left: 20px;
            top: 50%;
            transform: translateY(-50%);
        }
        .container {
            padding: 20px;
            background: white;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
            border-radius: 8px;
            margin-top: 20px;
        }
        .shopping-item {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px;
            margin-bottom: 10px;
            border-bottom: 1px solid #ccc;
        }
        .shopping-item .details {
            text-align: left;
            flex: 2;
        }
        .shopping-item .quantity {
            text-align: center;
            flex: 1;
        }
        .delete-button {
            background-color: #f44336;
            color: white;
            border: none;
            border-radius: 4px;
            padding: 5px 10px;
            cursor: pointer;
        }
        .delete-button:hover {
            background-color: #d32f2f;
        }
        .field {
            margin-bottom: 20px;
        }
        .field .control {
            margin-bottom: 10px;
        }
    </style>
</head>
<body>
    <header>
        <button onclick="location.href='/shopping/shopping_list'" class="back-button">Back to Shopping Lists</button>
    </header>
    <div class="container">
        <h1>Shopping List Details: {{ shopping_list.list_name }}</h1>
        {% if form %}
        <form method="POST" action="{{ url_for('shopping.shopping_list_detail', list_id=shopping_list.id) }}">
            {{ form.hidden_tag() }}
            <div class="field">
                <div class="control">
                    {{ form.newItem(class="input", placeholder="Add new item to list") }}
                </div>
            </div>
            <div class="field">
                <div class="control">
                    {{ form.itemQuantity(class="input", placeholder="Enter item quantity") }}
                </div>
            </div>
            <div class="field">
                <div class="control">
                    {{ form.itemUnits(class="input", placeholder="Enter units of item (g or ml)") }}
                </div>
            </div>
            <div>
                {{ form.submit(class="button is-info is-centered") }}
            </div>
        </form>
        {% endif %}
        <div class="shopping-list-details">
            <h2>List of Items</h2>
            {% for item in shopping_list.shopping_items %}
                <div class="shopping-item" id="shopping-item-{{ item.id }}">
                    <span class="details">Ingredients: {{ item.qfooditem.fooditem.name }}</span>
                    <span class="quantity">Quantity: {{ item.qfooditem.quantity }} {{ item.qfooditem.units }}</span>
                    <form action="{{ url_for('shopping.delete_item', item_id=item.id) }}" method="POST">
                        <button class="delete-button" type="submit">X</button>
                    </form>
                </div>
            {% endfor %}
        </div>
    </div>
</body>
</html>