recipes/forms.py
# Authored by: Faris, Joe, Yat Nam, Keirav
# utility functions for recipe management
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, TextAreaField, FieldList, FormField, SubmitField
from wtforms.validators import DataRequired

class IngredientForm(FlaskForm):
    food = StringField('Food', validators=[DataRequired()])
    quantity = IntegerField('Quantity', validators=[DataRequired()])
    unit = StringField('Unit', validators=[DataRequired()])

class RecipeForm(FlaskForm):
    name = StringField('Recipe Name', validators=[DataRequired()])
    method = TextAreaField('Method', validators=[DataRequired()])
    serves = IntegerField('Serving Size', validators=[DataRequired()])
    calories = IntegerField('Calories')
    ingredients = FieldList(FormField(IngredientForm), min_entries=1)
    submit = SubmitField('Add Recipe')

recipes/views.py
# Authored by: Keirav, Yat Nam, Joe, Jawaher, Faris
# View functions for recipe pages
from extensions import db
from models import Recipe, Ingredient, QuantifiedFoodItem, Rating, PantryItem, InUseRecipe, FoodItem, ShoppingItem, ShoppingList
from flask import Blueprint, render_template, request, redirect, url_for, flash, jsonify
from flask_login import login_required, current_user
from sqlalchemy import func

from recipes.forms import RecipeForm
from recipes.recipe_util import (create_recipe, create_or_get_food_item, create_and_get_qfid,
                                 delete_recipe_instance, update_recipe_rating, create_shopping_list_from_recipe,
                                 save_rating, complete_and_rate_recipe, get_pantry_dict, check_recipe_ingredients)

recipes_blueprint = Blueprint('recipes', __name__, template_folder='templates')

print("Template folder:", recipes_blueprint.template_folder)

# Filter system to sort recipes based on name, calories, rating, etc.
@recipes_blueprint.route('/recipes', methods=['GET'])
@login_required
def recipes():
    can_make_recipe_filter = request.args.get('can_make', type=bool)
    sort_by = request.args.get('sort_by', 'name')
    min_calories = request.args.get('min_calories', type=int)
    max_calories = request.args.get('max_calories', type=int)
    min_rating = request.args.get('min_rating', type=int)
    ingredient_filter = request.args.get('ingredient')
    serves_filter = request.args.get('serves', type=int)

    user_pantry = current_user.get_pantry()
    pantry_dict = {}
    for item in user_pantry:
        qfi = item.qfooditem
        if qfi.fooditem.name not in pantry_dict:
            pantry_dict[qfi.fooditem.name] = 0
        pantry_dict[qfi.fooditem.name] += qfi.quantity

    query = Recipe.query

    # Filter calories
    if min_calories is not None:
        query = query.filter(Recipe.calories >= min_calories)
    if max_calories is not None:
        query = query.filter(Recipe.calories <= max_calories)

    # Filter rating
    if min_rating is not None:
        query = query.filter(Recipe.rating >= min_rating)

    # Filter ingredients
    if ingredient_filter:
        query = query.join(Recipe.ingredients).join(Ingredient.qfooditem).join(FoodItem).filter(
            FoodItem.name.ilike(f"%{ingredient_filter}%"))

    # Filter servings
    if serves_filter:
        query = query.filter(Recipe.serves == serves_filter)

    # Sorting
    if sort_by == 'calories':
        query = query.order_by(Recipe.calories)
    elif sort_by == 'rating':
        query = query.order_by(Recipe.rating.desc())
    else:
        query = query.order_by(Recipe.name)

    # Execute the search
    recipes = query.all()

    # Consider which user can make the recipe
    if can_make_recipe_filter:
        filtered_recipes = []
        for recipe in recipes:
            can_make_recipe = True
            for ingredient in recipe.ingredients:
                ingredient_name = ingredient.get_name()
                if ingredient_name not in pantry_dict:
                    can_make_recipe = False
                    print(f"Missing ingredient: {ingredient_name}")
                    break
                if pantry_dict[ingredient_name] < ingredient.get_quantity():
                    can_make_recipe = False
                    print(f"Not enough quantity for ingredient: {ingredient_name}")
                    break
            if can_make_recipe:
                filtered_recipes.append(recipe)
        recipes = filtered_recipes

    return render_template('recipes/recipes.html', recipes=recipes)


# View own recipes
@recipes_blueprint.route('/your_recipes')
@login_required
def your_recipes():
    user_id = current_user.id
    recipes = Recipe.query.filter_by(user_id=user_id).all()
    return render_template('recipes/your_recipes.html', recipes=recipes)


@recipes_blueprint.route('/recipes_detail/<int:recipe_id>')
@login_required
def recipes_detail(recipe_id):
    """
    This function provides the details of a recipe, checks if the user can make it with their pantry items, and
    identifies any missing ingredients
    """
    # Retrieve the recipe by ID
    recipe = Recipe.query.get(recipe_id)

    # Retrieve all ingredients for the recipe
    ingredients = Ingredient.query.filter_by(recipe_id=recipe_id).all()

    # Retrieve the user's pantry items
    user_pantry = PantryItem.query.filter_by(user_id=current_user.id).all()

    # Convert pantry items to a dictionary format for easy read
    pantry_dict = get_pantry_dict(user_pantry)

    # Check if the user can make the recipe with their pantry items and identify any missing ingredients
    can_make_recipe, missing_ingredients = check_recipe_ingredients(ingredients, pantry_dict)

    return render_template('recipes/recipes_detail.html', recipe=recipe, ingredients=ingredients,
                           can_make_recipe=can_make_recipe, missing_ingredients=missing_ingredients)


# Add recipe
@recipes_blueprint.route('/add_recipes', methods=['GET', 'POST'])
@login_required
def add_recipes():
    if request.method == 'POST':
        # Get form data
        name = request.form['name']
        method = request.form['method']
        serves = request.form['serves']
        calories = request.form['calories']
        ingredients = []

        for i in range(len(request.form.getlist('ingredient[]'))):
            ingredients.append({
                "food": request.form.getlist('ingredient[]')[i],
                "quantity": request.form.getlist('quantity[]')[i],
                "unit": request.form.getlist('unit[]')[i],
            })

        create_recipe(name, method, serves, calories, ingredients)
        return redirect(url_for('recipes.recipes'))  # Ensure this redirects to the correct view
    else:
        return render_template('recipes/add_recipes.html')


# Edit own recipe
@recipes_blueprint.route('/edit_recipes/<int:recipe_id>', methods=['GET', 'POST'])
@login_required
def edit_recipes(recipe_id):
    recipe = Recipe.query.get_or_404(recipe_id)
    if request.method == 'POST':
        recipe.name = request.form['name']
        recipe.method = request.form['method']
        recipe.serves = request.form['serves']
        recipe.calories = request.form['calories']

        # Clear existing ingredients
        Ingredient.query.filter_by(recipe_id=recipe_id).delete()

        # Add new ingredients
        ingredients = zip(request.form.getlist('ingredient[]'), request.form.getlist('quantity[]'), request.form.getlist('unit[]'))
        for food, quantity, unit in ingredients:
            food_item = create_or_get_food_item(food)
            qfi = create_and_get_qfid(food_item.id, quantity, unit)
            new_ingredient = Ingredient(recipe_id=recipe_id, qfood_id=qfi)
            db.session.add(new_ingredient)

        db.session.commit()
        flash('Recipe updated successfully!', 'success')
        return redirect(url_for('recipes.recipes'))
    else:
        ingredients = [(i.qfooditem.fooditem.name, i.qfooditem.quantity, i.qfooditem.units) for i in recipe.ingredients]
        return render_template('recipes/edit_recipes.html', recipe=recipe, ingredients=ingredients)


# Delete own recipe
@recipes_blueprint.route('/delete_recipe/<int:recipe_id>')
@login_required
def delete_recipe(recipe_id):
    recipe_to_delete = Recipe.query.filter_by(id=recipe_id).first()
    delete_recipe_instance(recipe_to_delete)
    flash('Recipe deleted successfully!', 'success')
    return redirect(url_for('recipes.recipes'))


@recipes_blueprint.route('/rate_recipe/<int:recipe_id>', methods=['POST'])
@login_required
def rate_recipe(recipe_id):
    rating_value = request.form.get('rating')
    if not rating_value:
        flash('Please select a rating.', 'error')
        return redirect(url_for('recipes.recipes', recipe_id=recipe_id))

    # Use the utility function to save the rating
    save_rating(current_user.id, recipe_id, int(rating_value))
    flash('Thank you for rating!', 'success')

    # Update recipe rating using the utility function
    update_recipe_rating(recipe_id)

    return redirect(url_for('recipes.recipes', recipe_id=recipe_id))


@recipes_blueprint.route('/use_recipe/<int:recipe_id>', methods=['POST'])
@login_required
def use_recipe(recipe_id):
    recipe = Recipe.query.get(recipe_id)
    if not recipe:
        print(f"Recipe with ID {recipe_id} not found")
        return jsonify({'error': 'Recipe not found'}), 404

    user_pantry = PantryItem.query.filter_by(user_id=current_user.id).all()
    pantry_dict = {item.qfooditem.fooditem.name: item for item in user_pantry}

    # Debugging: Print the user's pantry
    print("User Pantry:")
    for item in user_pantry:
        qfi = QuantifiedFoodItem.query.get(item.qfood_id)
        print(f"Pantry Item: {qfi.fooditem.name}, Quantity: {qfi.quantity}, ID: {item.qfood_id}")

    # Debugging: Check if the user has enough ingredients
    print("Recipe Ingredients:")
    for ingredient in recipe.ingredients:
        qfi_ingredient = QuantifiedFoodItem.query.get(ingredient.qfood_id)
        if qfi_ingredient:
            ingredient_name = qfi_ingredient.fooditem.name
            ingredient_quantity = qfi_ingredient.quantity
            print(f"Ingredient: {ingredient_name}, Quantity: {ingredient_quantity}, ID: {ingredient.qfood_id}")

            pantry_item = pantry_dict.get(ingredient_name)
            if not pantry_item:
                print(f"Missing ingredient: {ingredient_name}")
                return jsonify({'error': f'Not enough {ingredient_name} in pantry'}), 400
            if pantry_item.qfooditem.quantity < ingredient_quantity:
                print(f"Not enough quantity for ingredient: {ingredient_name}")

templates/recipes/add_recipes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"> <!-- Font Awesome -->
    <title>Add Recipe</title>
    <style>
        h1 {
            background-color: #f6f6f6;
            padding: 10px;
            text-align: center;
            margin-bottom: 20px;
        }
        body {
            font-family: 'Roboto', sans-serif;
            background: #f7f7f7;
            margin: 0;
            padding: 20px;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }
        form {
            background: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            width: 300px;
        }
        label {
            font-weight: bold;
        }
        input, textarea {
            width: 100%;
            padding: 8px;
            margin-top: 8px;
            margin-bottom: 16px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }
        input:focus, textarea:focus {
            border-color: #0056b3;
            outline: none;
        }
        .actbutton {
            width: 100%;
            padding: 10px;
            background-color: #0056b3;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
        .actbutton:hover {
            background-color: #004494;
        }
        .ingredient-group {
            margin-bottom: 10px;
        }
        .add-button {
            background-color: #4CAF50; /* Green */
            margin-bottom: 20px;
            width: 100%;
            padding: 10px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
        .back-button {
            background-color: #0056b3;
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 4px;
            cursor: pointer;
            position: absolute;
            left: 10px;
            top: 10px;
        }
    </style>
</head>
<body>
<button class="back-button" onclick="location.href='/recipes/recipes'">Go Back</button>

    <form action="{{ url_for('recipes.add_recipes') }}" method="POST">
        <h1>Add a New Recipe</h1>
        <label for="name">Recipe Name:</label>
        <input type="text" id="name" name="name" required>

        <label for="method">Cooking Method:</label>
        <textarea id="method" name="method" required></textarea>

        <label for="serves">Serves:</label>
        <input type="number" id="serves" name="serves" required>

        <label for="calories">Calories:</label>
        <input type="number" id="calories" name="calories">

        <div id="ingredients-container">
            <label>Ingredients:</label>
            <div class="ingredient-group">
                <input type="text" name="ingredient[]" placeholder="Food" required>
                <input type="number" name="quantity[]" placeholder="Quantity" required>
                <input type="text" name="unit[]" placeholder="Unit (e.g., kg, g, L)" required>
            </div>
        </div>
        <button type="button" class="add-button" onclick="addIngredient()">Add More Ingredients</button>
        <button class='actbutton' type="submit">Add Recipe</button>
    </form>

    <script>
        function addIngredient() {
            const container = document.getElementById('ingredients-container');
            const group = document.createElement('div');
            group.className = 'ingredient-group';
            group.innerHTML = `
                <input type="text" name="ingredient[]" placeholder="Food" required>
                <input type="number" name="quantity[]" placeholder="Quantity" required>
                <input type="text" name="unit[]" placeholder="Unit (e.g., kg, g, L)" required>
            `;
            container.appendChild(group);
        }
    </script>
</body>
</html>


templates/recipes/complete_recipe.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"> <!-- Font Awesome -->
    <style>
        body {
            font-family: 'Roboto', sans-serif;
            background: #ffffff;
            margin: 0;
            text-align: center;
        }
        .back-button {
            background-color: #0056b3;
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 4px;
            cursor: pointer;
            position: absolute;
            left: 10px;
            top: 10px;
        }
        .rate-button {
            background-color: #28a745;
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 4px;
            cursor: pointer;
        }
        .box {
            padding: 20px;
            margin: 20px;
            background-color: #f8f8f8;
            border-radius: 8px;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
        }
    </style>
</head>
<body>
<div class="navbar">
    <button class="back-button" onclick="location.href='/recipes/in_use_recipes'">Go Back</button>
</div>
<div class="column is-6 is-offset-3">
    <h3 class="title">Rate Recipe</h3>
    <div class="box">
        <form action="{{ url_for('recipes.complete_recipe', recipe_id=recipe.id) }}" method="POST">
            <label for="rating">Rate this recipe:</label>
            <input type="number" id="rating" name="rating" min="1" max="5" required>
            <button type="submit" class="rate-button">Submit Rating</button>
        </form>
    </div>
</div>
</body>
</html>



templates/recipes/recipes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Main Recipes</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"> <!-- Font Awesome -->
    <style>
        body {
            font-family: 'Roboto', sans-serif;
            background: #f7f7f7;
            margin: 0;
            padding: 20px;
        }
        header {
            background-color: #f6f6f6;
            padding: 10px;
            text-align: center;
            margin-bottom: 20px;
        }
        header button {
            background: #0056b3;
            border: none;
            color: white;
            padding: 10px 20px;
            margin: 0 10px;
            border-radius: 4px;
            cursor: pointer;
        }
        header button:hover {
            background: #004494;
        }
        .recipebox {
            margin: 20px auto;
            background-color: #fff;
            padding: 20px;
            width: 80%;
            max-width: 800px;
            border-radius: 8px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.1);
            border: 1px solid #dcdcdc;
        }
        table {
            width: 100%;
            border-collapse: separate;
            border-spacing: 0 15px;
        }
        th, td {
            padding: 8px 12px;
            text-align: left;
            font-size: 16px;
        }
        th {
            color: #555;
        }
        td {
            border-bottom: 1px solid #eee;
        }
        .ratebutton {
            background: #16a085;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 18px;
            box-shadow: 0 2px 5px rgba(0,0,0,0.15);
            transition: background 0.3s ease-in-out;
        }
        .ratebutton:hover {
            background: #149174;
        }
        .sidebar {
            height: 100%;
            width: 0;
            position: fixed;
            z-index: 1001;
            top: 0;
            background-color: #111;
            overflow-x: hidden;
            transition: width 0.3s, padding 0.3s;
            padding-top: 60px;
        }
        .sidebar.left {
            left: 0;
        }
        .sidebar.right {
            right: 0;
        }
        .sidebar a {
            padding: 10px 0px;
            text-decoration: none;
            font-size: 25px;
            color: #818181;
            display: block;
            text-align: center;
            transition: 0.3s;
        }
        .sidebar a:hover {
            color: #f1f1f1;
        }
        .sidebar .closebtn {
            position: absolute;
            top: 0;
            font-size: 36px;
            right: 25px; /* Move close button to the right */
        }
        .sidebar form {
            color: white;
        }
        .sidebar h2, .sidebar h3, .sidebar label {
            color: white;
        }
        .sidebar select, .sidebar input {
            color: black;
        }
        .navbar {
            position: sticky;
            top: 0;
            width: 100%;
            background: #f6f6f6;
            z-index: 1000;
            padding: 10px 0;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
            display: flex;
            justify-content: space-between;
        }
        .navbar .openbtn {
            font-size: 20px;
            cursor: pointer;
            color: white;
            border: none;
            border-radius: 4px;
            background-color: #111;
            padding: 10px;
            margin-left: 20px;
        }
        .your-button {
            width: 200px;
            text-align: center;
            padding: 10px 20px;
            background-color: #3498db;
            color: white;
            font-size: 20px;
            border-radius: 4px;
            text-decoration: none;
            transition: background-color 0.3s ease-in-out;
        }
        .your-button:hover {
            background-color: #2980b9;
        }
        .rate-form {
            margin-top: 10px;
        }
        select {
            padding: 10px;
            border-radius: 4px;
            margin-right: 10px;
        }
        h3 {
            color: #E1DCDC;
        }
    </style>
</head>
<body>
<div class="navbar">
    <div>
        <button class="openbtn" onclick="toggleNav('mySidebar')">☰ Menu</button>
    </div>
    <div>
        <a href="{{ url_for('recipes.your_recipes') }}" class="your-button">My Recipes</a>
        <a href="{{ url_for('recipes.add_recipes') }}" class="your-button">Create Recipes</a>
        <a href="{{ url_for('recipes.in_use_recipes') }}" class="your-button">Using Recipes</a>
        <button class="openbtn" onclick="toggleNav('filterSidebar')">☰ Filter & Sort</button>
    </div>
</div>

<div id="mySidebar" class="sidebar left">
    <a href="javascript:void(0)" class="closebtn left" onclick="toggleNav('mySidebar')">×</a>
    <a href="/main-menu">Main</a>
    <a href="/pantry/items">My Pantry</a>
    <a href="/pantry/search">Food Browser</a>
    <a href="/shopping/shopping_list">Shopping List</a>
    <a href="/recipes/recipes">Recipes</a>
    <a href="/barcodes/add_barcode">Save a Barcode</a>
</div>

<div id="filterSidebar" class="sidebar right">
    <a href="javascript:void(0)" class="closebtn right" onclick="toggleNav('filterSidebar')">×</a>
    <form action="{{ url_for('recipes.recipes') }}" method="get">
        <h2>Filter & Sort Recipes</h2>
        <h3>Sort by:</h3>
        <select name="sort_by">
            <option value="name">Name</option>
            <option value="calories">Calories</option>
            <option value="rating">Rating</option>
        </select>

        <h3>Filter by Can Make:</h3>
        <label>
            <input type="checkbox" name="can_make" value="1" style="margin-bottom: 20px;">
            Can Make
        </label>

        <h3>Filter by Calories:</h3>
        <input type="number" name="min_calories" placeholder="Min Calories" style="margin-bottom: 10px;">
        <input type="number" name="max_calories" placeholder="Max Calories" style="margin-bottom: 20px;">

        <h3>Filter by Rating:</h3>
        <input type="number" name="min_rating" placeholder="Min Rating" style="margin-bottom: 20px;">

        <h3>Filter by Ingredients:</h3>
        <input type="text" name="ingredient" placeholder="Ingredient Name" style="margin-bottom: 20px;">

        <h3>Filter by Serves:</h3>
        <input type="number" name="serves" placeholder="Serves" style="margin-bottom: 20px;">

        <button type="submit" class="your-button">Apply Filters</button>
    </form>
</div>

{% for recipe in recipes %}
<div class="recipebox">
    <h2 class="recipe-name">
        <a href="{{ url_for('recipes.recipes_detail', recipe_id=recipe.id) }}" style="text-decoration: none; color: inherit;">
            {{ recipe.name }}
        </a>
    </h2>
    <table>
        <tr>
            <th>Serves:</th>
            <td>{{ recipe.serves }}</td>
        </tr>
        <tr>
            <th>Calories:</th>
            <td>{{ recipe.calories }} kcal</td>
        </tr>
        <tr>
            <th>Rating:</th>
            <td>{{ recipe.rating | default(0) }} / 5</td>
        </tr>
    </table>
    <form class="rate-form" action="{{ url_for('recipes.rate_recipe', recipe_id=recipe.id) }}" method="POST">
        <select name="rating">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
        </select>
        <button type="submit" class="ratebutton">Rate</button>
    </form>
</div>
{% endfor %}

<script>
    function toggleNav(sidebarId) {
        var sidebar = document.getElementById(sidebarId);
        if (sidebar.style.width === "250px" || sidebar.style.width === "300px") {
            sidebar.style.width = "0";
            sidebar.style.padding = "0";
        } else {
            if (sidebarId === 'mySidebar') {
                sidebar.style.width = "250px";
            } else {
                sidebar.style.width = "300px";
                sidebar.style.padding = "10px 20px";
            }
        }
    }
</script>

</body>
</html>

templates/recipes/your_recipes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Recipes</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"> <!-- Font Awesome -->
    <style>
        body {
            font-family: 'Roboto', sans-serif;
            background: #f7f7f7;
            margin: 0;
            padding: 20px;
        }
        h1 {
            text-align: center;
            font-size: 36px;
            font-weight: bold;
            text-shadow: 2px 2px 4px rgba(0,0,0,0.2);
            margin-top: 20px;
            margin-bottom: 20px;
            padding: 10px;
        }

        .recipebox {
            margin: 20px auto;
            background-color: #fff;
            padding: 20px;
            width: 80%;
            max-width: 800px;
            border-radius: 8px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.1);
            border: 1px solid #dcdcdc;
        }
        table {
            width: 100%;
            border-collapse: separate;
            border-spacing: 0 15px;
        }
        th, td {
            padding: 8px 12px;
            text-align: left;
            font-size: 16px;
        }
        th {
            color: #555;
        }
        td {
            border-bottom: 1px solid #eee;
        }
        .del-button {
            text-decoration: none;
            color: white;
            background-color: #f44336;
            padding: 10px 20px;
            border-radius: 4px;
            border: none;
            display: inline-block;
            cursor: pointer;
        }
        .del-button:hover {
            background-color: #d32f2f;
        }
        .edit-button {
            text-decoration: none;
            color: white;
            background-color: #f39c12;
            padding: 10px 20px;
            border-radius: 4px;
            border: none;
            display: inline-block;
            cursor: pointer;
        }
        .edit-button:hover {
            background-color: #e67e22;
        }
        .back-button {
            background-color: #0056b3;
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 4px;
            cursor: pointer;
            position: absolute;
            left: 10px;
            top: 10px;
        }
        .navbar {
            position: sticky;
            top: 0;
            width: 100%;
            background: #f6f6f6;
            z-index: 1000;
            padding: 30px 0;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
        }
    </style>
</head>
<body>
<div class="navbar">
        <button class="back-button" onclick="location.href='/recipes/recipes'">Go Back</button>
    </div>
    <h1>My Recipes</h1>
     {% for recipe in recipes %}
<div class="recipebox">
    <h2 class="recipe-name">
        <a href="{{ url_for('recipes.recipes_detail', recipe_id=recipe.id) }}" style="text-decoration: none; color: inherit;">
            {{ recipe.name }}
        </a>
    </h2>
    <table>
        <tr>
            <th>Serves:</th>
            <td>{{ recipe.serves }}</td>
        </tr>
        <tr>
            <th>Calories:</th>
            <td>{{ recipe.calories }} kcal</td>
        </tr>
        <tr>
            <th>Rating:</th>
            <td>{{ recipe.rating }} / 5</td>
        </tr>
    </table>
            <a href="{{ url_for('recipes.delete_recipe', recipe_id=recipe.id) }}" class="del-button" onclick="return confirm('Are you sure you want to delete this recipe?');">Delete</a>
             <a href="{{ url_for('recipes.edit_recipes', recipe_id=recipe.id) }}" class="edit-button" onclick="return confirm('Are you sure you want to edit this recipe?');">Edit</a>
        </div>
    {% endfor %}
</body>
<script>

</script>
</html>